version: '3'
services:
  dev:
    build: .
    volumes:
      - ./:/code
    environment:
     - OAUTH_APP_NAME
     - OAUTH_APP_ID
     - OAUTH_APP_SECRET
     - OAUTH_ACCESS_TOKEN
     - OAUTH_REFRESH_TOKEN
     - TEST_SHAREPOINT_SITE

